eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    healthcheck:
      enabled: true
    registerwitheureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
feign:
  httpclient:
    enabled: true
spring:
  application:
    name: client2
  profiles:
    active: test

